### ISSUE TITLE
REST service returns errors if filter with parameters isn't in the first place

### ISSUE THREAD

**Issue by janesch97** [Rhetos/Rhetos#142]
**Describe the bug**
Rhetos REST service returns an error if filters are applied in certain order.

**To Reproduce**
Execute a GET request with filters (filters with paremeters shouldn't be in the first place).

**Error message**
Command failed: ReadCommandInfo TestModule.TestSqlQueryable records, order by -Date, top 21, filters: Common.RowPermissionsReadItems, TestModule.TestSqlQueryableSearch "...", ID in "3 items: 7f45767e-5c03-4391-83a9-c374f7a06b67 ...". Rhetos.FrameworkException: EvidencijaPismena.PredmetUpozorenje does not implement a filter with parameter EvidencijaPismena.PredmetUpozorenjeSearch. There is a loader method with this parameter implemented: Try reordering filters to use the TestSqlQueryableSearch first.
   at Rhetos.Dom.DefaultConcepts.GenericRepository`1.FilterOrQuery(IEnumerable`1 items, Object parameter, Type parameterType) in D:\Development\GIT\Core\Rhetos\CommonConcepts\Plugins\Rhetos.Dom.DefaultConcepts\GenericRepository.cs:line 557
   at Rhetos.Dom.DefaultConcepts.GenericRepository`1.ExecuteGenericFilter(IEnumerable`1 genericFilter, Boolean preferQuery, IEnumerable`1 items) in D:\Development\GIT\Core\Rhetos\CommonConcepts\Plugins\Rhetos.Dom.DefaultConcepts\GenericRepository.cs:line 386
   at Rhetos.Dom.DefaultConcepts.GenericRepository`1.Read(Object parameter, Type parameterType, Boolean preferQuery) in D:\Development\GIT\Core\Rhetos\CommonConcepts\Plugins\Rhetos.Dom.DefaultConcepts\GenericRepository.cs:line 305
   at Rhetos.Dom.DefaultConcepts.ReadableRepositoryExtensions.Read[TEntity,TParameter](IReadableRepository`1 repository, TParameter parameter, Boolean preferQuery) in D:\Development\GIT\Core\Rhetos\CommonConcepts\Plugins\Rhetos.Dom.DefaultConcepts.Interfaces\IReadableRepository.cs:line 74
   at Rhetos.Processing.DefaultCommands.ServerCommandsUtility.ExecuteReadCommand(ReadCommandInfo commandInfo, GenericRepository`1 genericRepository) in D:\Development\GIT\Core\Rhetos\CommonConcepts\Plugins\Rhetos.Processing.DefaultCommands\ServerCommandsUtility.cs:line 129
   at Rhetos.Processing.DefaultCommands.ReadCommand.Execute(ICommandInfo commandInfo) in D:\Development\GIT\Core\Rhetos\CommonConcepts\Plugins\Rhetos.Processing.DefaultCommands\ReadCommand.cs:line 57
   at Rhetos.Processing.ProcessingEngine.ExecuteInner(IList`1 commands, Guid executionId) in C:\My Projects\Rhetos\Source\Rhetos.Processing\ProcessingEngine.cs:line 145

**Expected behavior**
REST service returns results independently of filter order.

**Comment by bantolov** [comment]
The error you are getting is partially describing the issue but it should be explained better.

```
{ENTITY} does not implement a filter with parameter {FILTERNAME}.
There is a loader method with this parameter implemented:
Try reordering filters to use the {FILTERNAME} first.
```

I  am guessing that you have `FilterBy TestSqlQueryableSearch` in your DSL script, and this REST request is trying to use it.

### Why did the server return and error

One cause of misunderstanding here is that `FilterBy` is not a composable filter (actually it should be called a **loader** instead of a **filter**): is cannot receive some previously filtered data and apply additional constraints to the dataset. It can only load the data from scratch!

Now the issue here is that this web request has 3 filters applied (as shown in the error message):

1. RowPermissionsReadItems
2. FilterBy TestModule.TestSqlQueryableSearch
3. ID in [list of 3 items]

The server will always process the filters in the given order. Now, `RowPermissionsReadItems` and filter by ID list can be applied to any input dataset, but `FilterBy` does not have an input data, that is why it must be first in the list to initialize (load) the data, then other filters will be able to filter the data additionally.

### Solution

In your case, I am not sure that moving the `TestSqlQueryableSearch` to the first position is a good solution, because it will create an overhead of loading excess data from the database, only to select 3 records by ID later. I am also not sure if the RowPermissions would work on the loaded data, it is designed to work on LINQ queries and in database.

* A) The best solution is probably to change the implementation of TestSqlQueryableSearch to use `ComposableFilterBy` instead of `FilterBy`.
* B) Alternatively, you could manually integrate all other filters into the TestSqlQueryableSearch. So that the REST request uses only one filter with more parameters.

One more observation: if you have a generic client code that adds "RowPermissionsReadItems" filter to the web request, you should move it to the **last position, to improve performance**. See the notes at [Reading data with row permissions](https://github.com/Rhetos/Rhetos/wiki/RowPermissions-concept#client-code---reading-data-with-row-permissions).
