### ISSUE TITLE
Migration script doesn't find newly added column

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#155]
Hi guys:

My entity is:

```c
Entity DocumentAllowedStatusTransition
    {
        AuditAndLoggingAll;

        Reference DocumentType MasterData.DocumentType {Required;}
        Reference StatusFrom MasterData.WarehouseDocumentStatus {Required;}
        Reference StatusTo MasterData.WarehouseDocumentStatus {Required;}
        Reference WarehouseType MasterData.WarehouseType {Required;}
        Reference TallyType MasterData.TallyType;
        Bool IsOverride; !!!THIS IS A NEWLY ADDED PROPERTY
  }
```

And my migration script is: 

```sql
/*DATAMIGRATION AAAACE17-EA5D-4C20-9281-0561B3699112*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Warehouse', 'DocumentAllowedStatusTransition';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'DocumentTypeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'StatusFromID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'StatusToID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'WarehouseTypeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'TallyTypeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'ClaimID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'Active', 'bit';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'IsOverride', 'bit';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'CreatedBy', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'LastModifiedBy', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'LastModifiedTime', 'datetime';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'CreatedTime', 'datetime';


UPDATE _Warehouse.DocumentAllowedStatusTransition set IsOverride = 1 where ClaimID Is not null;

EXEC Rhetos.DataMigrationApplyMultiple 'Warehouse', 'DocumentAllowedStatusTransition', 'ID, WarehouseTypeID, TallyTypeID, ClaimID, IsOverride, DocumentTypeID, StatusFromID, StatusToID, Active, CreatedBy, LastModifiedBy, LastModifiedTime, CreatedTime';
```

While building i get:

```
> [Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\05_WarehouseDocumentItemState.sql (tag A5623D30-8185-4609-A977-02929EFEBC99)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\42.0_MasterData_DeviatioNReason.sql (tag CDCEA942-DAFA-4D44-A983-369755379840)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\43.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 96CCCE17-EA5D-4C20-9281-0561B36992DF)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\44_MasterData_WarehouseDocumentStatus.sql (tag 664B04FF-D971-4A2F-984C-74FE10160409)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\45.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 96ACCE17-EA5D-4C20-9281-0561B36992DA)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\46.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 46CCCE17-EA5D-4C20-9281-0561B36992DA)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\47.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 46CCCE17-EA5D-4C20-9281-0561B3699112)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\48.0_Warehouse_DocumentAllowedStatusTransition.sql (tag AAAACE17-EA5D-4C20-9281-0561B3699112)
[Info] DataMigration: Executing script in an incorrect order LTSP-ZGSped\8.0\49.0_Warehouse_DocumentAllowedStatusTransition.sql (tag E52200C9-27AB-4D70-B4B3-A269E21627CD)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\05_WarehouseDocumentItemState.sql (tag A5623D30-8185-4609-A977-02929EFEBC99)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\42.0_MasterData_DeviatioNReason.sql (tag CDCEA942-DAFA-4D44-A983-369755379840)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\43.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 96CCCE17-EA5D-4C20-9281-0561B36992DF)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\44_MasterData_WarehouseDocumentStatus.sql (tag 664B04FF-D971-4A2F-984C-74FE10160409)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\45.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 96ACCE17-EA5D-4C20-9281-0561B36992DA)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\46.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 46CCCE17-EA5D-4C20-9281-0561B36992DA)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\47.0_Warehouse_DocumentAllowedStatusTransition.sql (tag 46CCCE17-EA5D-4C20-9281-0561B3699112)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\48.0_Warehouse_DocumentAllowedStatusTransition.sql (tag AAAACE17-EA5D-4C20-9281-0561B3699112)
[Info] DataMigration: Execute LTSP-ZGSped\8.0\49.0_Warehouse_DocumentAllowedStatusTransition.sql (tag E52200C9-27AB-4D70-B4B3-A269E21627CD)
[Error] MsSqlExecuter: Unable to execute SQL query:
--Name: LTSP-ZGSped\8.0\48.0_Warehouse_DocumentAllowedStatusTransition.sql
/*DATAMIGRATION AAAACE17-EA5D-4C20-9281-0561B3699112*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Warehouse', 'DocumentAllowedStatusTransition';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'DocumentTypeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'StatusFromID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'StatusToID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'WarehouseTypeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'TallyTypeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'ClaimID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'Active', 'bit';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'IsOverride', 'bit';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'CreatedBy', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'LastModifiedBy', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'LastModifiedTime', 'datetime';
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'CreatedTime', 'datetime';


UPDATE _Warehouse.DocumentAllowedStatusTransition set IsOverride = 1 where ClaimID Is not null;


EXEC Rhetos.DataMigrationApplyMultiple 'Warehouse', 'DocumentAllowedStatusTransition', 'ID, WarehouseTypeID, TallyTypeID, ClaimID, IsOverride, DocumentTypeID, StatusFromID, StatusToID, Active, CreatedBy, LastModifiedBy, LastModifiedTime, CreatedTime';
[Error] MsSqlExecuter: SqlException has occurred in 'LTSP-ZGSped\8.0\48.0_Warehouse_DocumentAllowedStatusTransition.sql':
Msg 207, Level 16, State 1, Line 20
Invalid column name 'IsOverride'.
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'IsOverride'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Rhetos.Persistence.MsSqlExecuter.<>c__DisplayClass8_0.<ExecuteSql>b__1(DbCommand com) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 95
   at Rhetos.Persistence.MsSqlExecuter.SafeExecuteCommand(Action`1 action, Boolean useTransaction) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 218
ClientConnectionId:7a56a74a-b7a1-4527-bc1a-2ee5b791c5ca
Error Number:207,State:1,Class:16
[Error] DeployPackages: Rhetos.FrameworkException: SqlException has occurred in 'LTSP-ZGSped\8.0\48.0_Warehouse_DocumentAllowedStatusTransition.sql':
Msg 207, Level 16, State 1, Line 20
Invalid column name 'IsOverride'.
 ---> System.Data.SqlClient.SqlException: Invalid column name 'IsOverride'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Rhetos.Persistence.MsSqlExecuter.<>c__DisplayClass8_0.<ExecuteSql>b__1(DbCommand com) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 95
   at Rhetos.Persistence.MsSqlExecuter.SafeExecuteCommand(Action`1 action, Boolean useTransaction) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 218
   --- End of inner exception stack trace ---
   at Rhetos.Persistence.MsSqlExecuter.SafeExecuteCommand(Action`1 action, Boolean useTransaction) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 229
   at Rhetos.Persistence.MsSqlExecuter.ExecuteSql(IEnumerable`1 commands, Boolean useTransaction, Action`1 beforeExecute, Action`1 afterExecute) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 74
   at Rhetos.Utilities.SqlTransactionBatches.Execute(IEnumerable`1 sqlScripts) in C:\My Projects\Rhetos\Source\Rhetos.Utilities\SqlTransactionBatches.cs:line 120
   at Rhetos.Deployment.DataMigration.ApplyToDatabase(List`1 toRemove, List`1 toExecute) in C:\My Projects\Rhetos\Source\Rhetos.Deployment\DataMigration.cs:line 122
   at Rhetos.Deployment.DataMigration.ExecuteDataMigrationScripts() in C:\My Projects\Rhetos\Source\Rhetos.Deployment\DataMigration.cs:line 91
   at Rhetos.Deployment.ApplicationGenerator.ExecuteGenerators(Boolean deployDatabaseOnly) in C:\My Projects\Rhetos\Source\Rhetos.Deployment\ApplicationGenerator.cs:line 110
   at DeployPackages.Program.GenerateApplication(ILogger logger, DeployArguments arguments) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 184
   at DeployPackages.Program.Main(String[] args) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 70
Info: 
The system cannot find the batch label specified - Error0
```

**Comment by bantolov** [comment]
Test the script by executing it manually in SSMS (make sure to add `BEGIN TRAN` at the beginning and `ROLLBACK` at the end).

The error might be caused by missing `GO` after the last `EXEC Rhetos.DataMigrationUse`, so the UPDATE SQL command does not "see" the new columns.

```sql
...
EXEC Rhetos.DataMigrationUse 'Warehouse', 'DocumentAllowedStatusTransition', 'CreatedTime', 'datetime';
GO

UPDATE _Warehouse.DocumentAllowedStatusTransition set IsOverride = 1 where ClaimID Is not null;
...
```

**Comment by ikudeljnj** [comment]
Rhetos.Utilities.dll!Rhetos.Utilities.ExceptionsUtility.Rethrow(System.Exception exception) Line 58	C#
 	ServerDom.Repositories.dll!Warehouse._Helper.Document_Materialized_Repository.Save(System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized> insertedNew, System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized> updatedNew, System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized> deletedIds, bool checkUserPermissions) Line 97621	C#
 	[External Code]	
 	Rhetos.Utilities.dll!Rhetos.Utilities.ExceptionsUtility.InvokeEx(System.Reflection.MethodInfo method, object obj, object[] parameters) Line 37	C#
 	Rhetos.Dom.DefaultConcepts.dll!Rhetos.Dom.DefaultConcepts.GenericRepository<Warehouse.Document_Materialized>.Save(System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized> insertNew, System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized> updateNew, System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized> deleteIds, bool checkUserPermissions) Line 575	C#
 	Rhetos.Dom.DefaultConcepts.dll!Rhetos.Dom.DefaultConcepts.GenericRepository<Warehouse.Document_Materialized>.InsertOrUpdateOrDelete(System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized> newItems, System.Collections.Generic.IComparer<Warehouse.Document_Materialized> sameRecord, System.Func<Warehouse.Document_Materialized, Warehouse.Document_Materialized, bool> sameValue, object filterLoad, System.Action<Warehouse.Document_Materialized, Warehouse.Document_Materialized> assign, Rhetos.Dom.DefaultConcepts.GenericRepository<Warehouse.Document_Materialized>.BeforeSave beforeSave) Line 807	C#
 	ServerDom.Repositories.dll!Warehouse._Helper.Document_Materialized_Repository.RecomputeFromDocument(object filterLoad, System.Func<System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized>, System.Collections.Generic.IEnumerable<Warehouse.Document_Materialized>> filterSave) Line 97692	C#
 	ServerDom.Repositories.dll!Warehouse._Helper.Receipt_Repository.Save(System.Collections.Generic.IEnumerable<Warehouse.Receipt> insertedNew, System.Collections.Generic.IEnumerable<Warehouse.Receipt> updatedNew, System.Collections.Generic.IEnumerable<Warehouse.Receipt> deletedIds, bool checkUserPermissions) Line 74387	C#
 	Rhetos.Dom.DefaultConcepts.Interfaces.dll!Rhetos.Dom.DefaultConcepts.WritableRepositoryExtensions.Delete<Warehouse.Receipt>(Rhetos.Dom.DefaultConcepts.IWritableRepository<Warehouse.Receipt> repository, System.Collections.Generic.IEnumerable<Warehouse.Receipt> deleteIds, bool checkUserPermissions) Line 64	C#
 	ServerDom.Repositories.dll!Warehouse._Helper.DeleteReceipt_Repository.Execute.AnonymousMethod__0(Warehouse.DeleteReceipt parameter, Common.DomRepository repository, Rhetos.Utilities.IUserInfo userInfo) Line 72671	C#
 	ServerDom.Repositories.dll!Warehouse._Helper.DeleteReceipt_Repository.Execute(Warehouse.DeleteReceipt actionParameter) Line 72680	C#
>	ServerDom.Repositories.dll!Warehouse._Helper.DeleteReceipt_Repository.Rhetos.Dom.DefaultConcepts.IActionRepository.Execute(object actionParameter) Line 72693	C#
 	Rhetos.Processing.DefaultCommands.dll!Rhetos.Processing.DefaultCommands.ExecuteActionCommand.Execute(Rhetos.Processing.ICommandInfo commandInfo) Line 48	C#
 	Rhetos.Processing.dll!Rhetos.Processing.ProcessingEngine.ExecuteInner(System.Collections.Generic.IList<Rhetos.Processing.ICommandInfo> commands, System.Guid executionId) Line 145	C#
 	Rhetos.Processing.dll!Rhetos.Processing.ProcessingEngine.Execute(System.Collections.Generic.IList<Rhetos.Processing.ICommandInfo> commands) Line 89	C#
 	Rhetos.RestGenerator.dll!Rhetos.RestGenerator.Utilities.ServiceUtility.Execute<Warehouse.DeleteReceipt>(Warehouse.DeleteReceipt action) Line 267	C#
 	RestService.dll!Rhetos.Rest.RestServiceWarehouseDeleteReceipt.ExecuteWarehouseDeleteReceipt(Warehouse.DeleteReceipt action) Line 24091	C#
 	[External Code]

**Comment by ikudeljnj** [comment]
This solves the error, thanks!
