### ISSUE TITLE
Generics vs Rhetos

### ISSUE THREAD

**Issue by JosipBaketaric** [Rhetos/Rhetos#172]
**Describe the bug**
When using a generic method (from outside DLL) which for constraint has Rhetos generated class, Rhetos deploy fails.

**To Reproduce**
create method in DLL:
private T TestMethod<T>(T src) where T : ClassDefinedInRhetosScript
{
    return src;
}

deploy Rhetos and expect an error.

**Error message**
[Error] DeployPackages: Rhetos.FrameworkException: Check for missing assembly or unsupported assembly version. Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
FileNotFoundException: Could not load file or assembly 'ServerDom.Model, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by ibarban** [comment]
Hi,

Cold it be that the problem is because the generic method is not defined correctly?
I think that it should be this way
```
private T TestMethod<T>(T src) where T : ClassDefinedInRhetosScript
{
return src;
}
```
Can you try it this way and if the problem still persist can you tell me where do you define the generic method and what version of Rhetos are you using?

**Comment by JosipBaketaric** [comment]
Hi,
I wrote this generic method wrong here. In my code, it is like you wrote.
 I define it in a separate DLL, and method that I call from Rhetos is using it. But even if it is not used, it still doesn't work.
Versions:
  <package id="Rhetos.CommonConcepts" version="2.8.0" />  
  <package id="Rhetos.AfterDeploy" version="1.1.0" />
  <package id="Rhetos.RestGenerator" version="2.5.0" />
  <package id="Rhetos.I18NFormatter" version="1.0.0" />
  <package id="Rhetos.AspNetFormsAuth" version="2.2.1" />
  <package id="I18N" version="2.1.14" />
  <package id="Rhetos.LightDMS" version="1.7.0" />

**Comment by ibarban** [comment]
In what step does this error happens?
Can you post the entire DeployPackages log?

**Comment by JosipBaketaric** [comment]
2019-08-01 09:35:23.3420|TRACE|DeployPackages|Moving old generated files to cache.
2019-08-01 09:35:23.5118|TRACE|DeployPackages|Getting packages.
2019-08-01 09:35:23.5547|TRACE|PackageDownloader|Not looking for Modules (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:23.7143|TRACE|PackageDownloader|Downloading NuGet package Modules 1.0.0 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:24.4400|TRACE|NuGet|Installing 'Modules 1.0.0'.
2019-08-01 09:35:24.8361|TRACE|NuGet|Successfully installed 'Modules 1.0.0'.
2019-08-01 09:35:24.8770|TRACE|PackageDownloader|Not looking for Algorithms (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:24.8889|TRACE|PackageDownloader|Downloading NuGet package Algorithms 1.0.3 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:25.0146|TRACE|NuGet|Installing 'Algorithms 1.0.3'.
2019-08-01 09:35:25.0984|TRACE|NuGet|Successfully installed 'Algorithms 1.0.3'.
2019-08-01 09:35:27.4742|TRACE|PackageDownloader|Downloading NuGet package Rhetos.CommonConcepts 2.8.0 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:28.1654|TRACE|NuGet|Installing 'Rhetos.CommonConcepts 2.8.0'.
2019-08-01 09:35:28.6534|TRACE|NuGet|Successfully installed 'Rhetos.CommonConcepts 2.8.0'.
2019-08-01 09:35:28.8698|TRACE|PackageDownloader|Downloading NuGet package Rhetos.AfterDeploy 1.1.0 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:28.9566|TRACE|NuGet|Installing 'Rhetos.AfterDeploy 1.1.0'.
2019-08-01 09:35:29.0264|TRACE|NuGet|Successfully installed 'Rhetos.AfterDeploy 1.1.0'.
2019-08-01 09:35:29.3874|TRACE|PackageDownloader|Downloading NuGet package Rhetos.RestGenerator 2.5.0 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:29.5131|TRACE|NuGet|Installing 'Rhetos.RestGenerator 2.5.0'.
2019-08-01 09:35:29.6368|TRACE|NuGet|Successfully installed 'Rhetos.RestGenerator 2.5.0'.
2019-08-01 09:35:29.8672|TRACE|PackageDownloader|Downloading NuGet package Rhetos.I18NFormatter 1.0.0 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:29.8931|TRACE|NuGet|Installing 'Rhetos.I18NFormatter 1.0.0'.
2019-08-01 09:35:29.9848|TRACE|NuGet|Successfully installed 'Rhetos.I18NFormatter 1.0.0'.
2019-08-01 09:35:30.4177|TRACE|PackageDownloader|Downloading NuGet package Rhetos.AspNetFormsAuth 2.2.1 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:31.0261|TRACE|NuGet|Installing 'Rhetos.AspNetFormsAuth 2.2.1'.
2019-08-01 09:35:31.4524|TRACE|NuGet|Successfully installed 'Rhetos.AspNetFormsAuth 2.2.1'.
2019-08-01 09:35:31.8705|TRACE|PackageDownloader|Downloading NuGet package i18n 2.1.14 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:32.4509|TRACE|NuGet|Installing 'i18n 2.1.14'.
2019-08-01 09:35:32.9117|TRACE|NuGet|Successfully installed 'i18n 2.1.14'.
2019-08-01 09:35:33.3375|TRACE|PackageDownloader|Downloading NuGet package Rhetos.LightDMS 1.7.0 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:33.6098|TRACE|NuGet|Installing 'Rhetos.LightDMS 1.7.0'.
2019-08-01 09:35:33.7485|TRACE|NuGet|Successfully installed 'Rhetos.LightDMS 1.7.0'.
2019-08-01 09:35:33.7574|TRACE|PackageDownloader|Not looking for MasterData (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:33.7903|TRACE|PackageDownloader|Downloading NuGet package MasterData 1.0.2 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:33.8262|TRACE|NuGet|Installing 'MasterData 1.0.2'.
2019-08-01 09:35:34.3548|TRACE|NuGet|Successfully installed 'MasterData 1.0.2'.
2019-08-01 09:35:34.3548|TRACE|PackageDownloader|Not looking for GeneralLedger (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:34.3778|TRACE|PackageDownloader|Downloading NuGet package GeneralLedger 1.0.17 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:34.4127|TRACE|NuGet|Installing 'GeneralLedger 1.0.17'.
2019-08-01 09:35:35.0989|TRACE|NuGet|Successfully installed 'GeneralLedger 1.0.17'.
2019-08-01 09:35:35.1079|TRACE|PackageDownloader|Not looking for Assets (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:35.1308|TRACE|PackageDownloader|Downloading NuGet package Assets 1.0.0 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:35.1647|TRACE|NuGet|Installing 'Assets 1.0.0'.
2019-08-01 09:35:35.5846|TRACE|NuGet|Successfully installed 'Assets 1.0.0'.
2019-08-01 09:35:35.5956|TRACE|PackageDownloader|Not looking for Contracts (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:35.6115|TRACE|PackageDownloader|Downloading NuGet package Contracts 1.0.0 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:35.6434|TRACE|NuGet|Installing 'Contracts 1.0.0'.
2019-08-01 09:35:35.7501|TRACE|NuGet|Successfully installed 'Contracts 1.0.0'.
2019-08-01 09:35:35.7581|TRACE|PackageDownloader|Not looking for PriceLists (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:35.7731|TRACE|PackageDownloader|Downloading NuGet package PriceLists 1.0.0 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:35.8120|TRACE|NuGet|Installing 'PriceLists 1.0.0'.
2019-08-01 09:35:35.8299|TRACE|NuGet|Successfully installed 'PriceLists 1.0.0'.
2019-08-01 09:35:35.8409|TRACE|PackageDownloader|Not looking for TMLShared (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:35.8559|TRACE|PackageDownloader|Downloading NuGet package TMLShared 1.0.0 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:35.8908|TRACE|NuGet|Installing 'TMLShared 1.0.0'.
2019-08-01 09:35:35.9337|TRACE|NuGet|Successfully installed 'TMLShared 1.0.0'.
2019-08-01 09:35:35.9337|TRACE|PackageDownloader|Not looking for Security (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:35.9576|TRACE|PackageDownloader|Downloading NuGet package Security 1.0.1 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:36.0045|TRACE|NuGet|Installing 'Security 1.0.1'.
2019-08-01 09:35:36.1152|TRACE|NuGet|Successfully installed 'Security 1.0.1'.
2019-08-01 09:35:36.1241|TRACE|PackageDownloader|Not looking for PostingScheme (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:36.1381|TRACE|PackageDownloader|Downloading NuGet package PostingScheme 1.0.0 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:36.1800|TRACE|NuGet|Installing 'PostingScheme 1.0.0'.
2019-08-01 09:35:36.2059|TRACE|NuGet|Successfully installed 'PostingScheme 1.0.0'.
2019-08-01 09:35:36.2149|TRACE|PackageDownloader|Not looking for AccountPayables (version not specified) in packages cache because the request does not specify an exact version.
2019-08-01 09:35:36.2289|TRACE|PackageDownloader|Downloading NuGet package AccountPayables 1.0.0 from C:\Business\BGA.All\backend\_build\RhetosPackages.
2019-08-01 09:35:36.2678|TRACE|NuGet|Installing 'AccountPayables 1.0.0'.
2019-08-01 09:35:36.3585|TRACE|NuGet|Successfully installed 'AccountPayables 1.0.0'.
2019-08-01 09:35:36.3665|TRACE|PackageDownloader|Not looking for WindowsAzure.Storage 7.2.1 in packages cache because the request does not specify an exact version.
2019-08-01 09:35:36.3665|TRACE|PackageDownloader|There is no legacy file WindowsAzure.Storage_7_2_1.zip in RhetosPackages.
2019-08-01 09:35:37.0683|TRACE|PackageDownloader|Downloading NuGet package WindowsAzure.Storage 7.2.1 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:37.2136|TRACE|NuGet|Installing 'WindowsAzure.Storage 7.2.1'.
2019-08-01 09:35:38.0245|TRACE|NuGet|Successfully installed 'WindowsAzure.Storage 7.2.1'.
2019-08-01 09:35:38.0245|TRACE|PackageDownloader|Not looking for Microsoft.Data.OData 5.6.4 in packages cache because the request does not specify an exact version.
2019-08-01 09:35:38.0444|TRACE|PackageDownloader|There is no legacy file Microsoft.Data.OData_5_6_4.zip in RhetosPackages.
2019-08-01 09:35:38.5487|TRACE|PackageDownloader|Downloading NuGet package Microsoft.Data.OData 5.6.4 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:40.1499|TRACE|NuGet|Installing 'Microsoft.Data.OData 5.6.4'.
2019-08-01 09:35:41.0256|TRACE|NuGet|Successfully installed 'Microsoft.Data.OData 5.6.4'.
2019-08-01 09:35:41.0485|TRACE|PackageDownloader|Not looking for Newtonsoft.Json 6.0.8 in packages cache because the request does not specify an exact version.
2019-08-01 09:35:41.0575|TRACE|PackageDownloader|There is no legacy file Newtonsoft.Json_6_0_8.zip in RhetosPackages.
2019-08-01 09:35:41.5732|TRACE|PackageDownloader|Downloading NuGet package Newtonsoft.Json 6.0.8 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:42.8180|TRACE|NuGet|Installing 'Newtonsoft.Json 6.0.8'.
2019-08-01 09:35:43.8617|TRACE|NuGet|Successfully installed 'Newtonsoft.Json 6.0.8'.
2019-08-01 09:35:43.8737|TRACE|PackageDownloader|Not looking for Microsoft.Data.Services.Client 5.6.4 in packages cache because the request does not specify an exact version.
2019-08-01 09:35:43.8867|TRACE|PackageDownloader|There is no legacy file Microsoft.Data.Services.Client_5_6_4.zip in RhetosPackages.
2019-08-01 09:35:44.4272|TRACE|PackageDownloader|Downloading NuGet package Microsoft.Data.Services.Client 5.6.4 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:44.5300|TRACE|NuGet|Installing 'Microsoft.Data.Services.Client 5.6.4'.
2019-08-01 09:35:45.3489|TRACE|NuGet|Successfully installed 'Microsoft.Data.Services.Client 5.6.4'.
2019-08-01 09:35:45.3569|TRACE|PackageDownloader|Not looking for Microsoft.Azure.KeyVault.Core 1.0.0 in packages cache because the request does not specify an exact version.
2019-08-01 09:35:45.3678|TRACE|PackageDownloader|There is no legacy file Microsoft.Azure.KeyVault.Core_1_0_0.zip in RhetosPackages.
2019-08-01 09:35:45.7492|TRACE|PackageDownloader|Downloading NuGet package Microsoft.Azure.KeyVault.Core 1.0.0 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:45.8310|TRACE|NuGet|Installing 'Microsoft.Azure.KeyVault.Core 1.0.0'.
2019-08-01 09:35:45.8668|TRACE|NuGet|Successfully installed 'Microsoft.Azure.KeyVault.Core 1.0.0'.
2019-08-01 09:35:46.3509|TRACE|PackageDownloader|Downloading NuGet package System.Spatial 5.6.4 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:46.8138|TRACE|NuGet|Installing 'System.Spatial 5.6.4'.
2019-08-01 09:35:47.0651|TRACE|NuGet|Successfully installed 'System.Spatial 5.6.4'.
2019-08-01 09:35:47.5069|TRACE|PackageDownloader|Downloading NuGet package Microsoft.Data.Edm 5.6.4 from https://www.nuget.org/api/v2/.
2019-08-01 09:35:48.1502|TRACE|NuGet|Installing 'Microsoft.Data.Edm 5.6.4'.
2019-08-01 09:35:48.4873|TRACE|NuGet|Successfully installed 'Microsoft.Data.Edm 5.6.4'.
2019-08-01 09:35:48.9560|TRACE|Packages|Rhetos 2.8.0 (requested from Rhetos framework) in C:\Business\BGA.All\backend\_build.
2019-08-01 09:35:48.9660|TRACE|Packages|MasterData 1.0.2 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\MasterData.1.0.2.
2019-08-01 09:35:48.9760|TRACE|Packages|Rhetos.CommonConcepts 2.8.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Rhetos.CommonConcepts.2.8.0.
2019-08-01 09:35:48.9760|TRACE|Packages|Rhetos.AfterDeploy 1.1.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Rhetos.AfterDeploy.1.1.0.
2019-08-01 09:35:48.9919|TRACE|Packages|Algorithms 1.0.3 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Algorithms.1.0.3.
2019-08-01 09:35:49.0079|TRACE|Packages|Modules 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Modules.1.0.0.
2019-08-01 09:35:49.0079|TRACE|Packages|GeneralLedger 1.0.17 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\GeneralLedger.1.0.17.
2019-08-01 09:35:49.0238|TRACE|Packages|Assets 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Assets.1.0.0.
2019-08-01 09:35:49.0238|TRACE|Packages|AccountPayables 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\AccountPayables.1.0.0.
2019-08-01 09:35:49.0408|TRACE|Packages|Contracts 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Contracts.1.0.0.
2019-08-01 09:35:49.0408|TRACE|Packages|i18n 2.1.14 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\i18n.2.1.14.
2019-08-01 09:35:49.0568|TRACE|Packages|Microsoft.Azure.KeyVault.Core 1.0.0 (requested from package WindowsAzure.Storage) in C:\Business\BGA.All\backend\_build\PackagesCache\Microsoft.Azure.KeyVault.Core.1.0.0.
2019-08-01 09:35:49.0568|TRACE|Packages|Microsoft.Data.Edm 5.6.4 (requested from package Microsoft.Data.OData) in C:\Business\BGA.All\backend\_build\PackagesCache\Microsoft.Data.Edm.5.6.4.
2019-08-01 09:35:49.0727|TRACE|Packages|System.Spatial 5.6.4 (requested from package Microsoft.Data.OData) in C:\Business\BGA.All\backend\_build\PackagesCache\System.Spatial.5.6.4.
2019-08-01 09:35:49.0727|TRACE|Packages|Microsoft.Data.OData 5.6.4 (requested from package WindowsAzure.Storage) in C:\Business\BGA.All\backend\_build\PackagesCache\Microsoft.Data.OData.5.6.4.
2019-08-01 09:35:49.0887|TRACE|Packages|Microsoft.Data.Services.Client 5.6.4 (requested from package WindowsAzure.Storage) in C:\Business\BGA.All\backend\_build\PackagesCache\Microsoft.Data.Services.Client.5.6.4.
2019-08-01 09:35:49.0887|TRACE|Packages|Newtonsoft.Json 6.0.8 (requested from package WindowsAzure.Storage) in C:\Business\BGA.All\backend\_build\PackagesCache\Newtonsoft.Json.6.0.8.
2019-08-01 09:35:49.1053|TRACE|Packages|PostingScheme 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\PostingScheme.1.0.0.
2019-08-01 09:35:49.1053|TRACE|Packages|PriceLists 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\PriceLists.1.0.0.
2019-08-01 09:35:49.1212|TRACE|Packages|Rhetos.AspNetFormsAuth 2.2.1 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Rhetos.AspNetFormsAuth.2.2.1.
2019-08-01 09:35:49.1212|TRACE|Packages|Rhetos.I18NFormatter 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Rhetos.I18NFormatter.1.0.0.
2019-08-01 09:35:49.1372|TRACE|Packages|WindowsAzure.Storage 7.2.1 (requested from package Rhetos.LightDMS) in C:\Business\BGA.All\backend\_build\PackagesCache\WindowsAzure.Storage.7.2.1.
2019-08-01 09:35:49.1372|TRACE|Packages|Rhetos.LightDMS 1.7.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Rhetos.LightDMS.1.7.0.
2019-08-01 09:35:49.1542|TRACE|Packages|Rhetos.RestGenerator 2.5.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Rhetos.RestGenerator.2.5.0.
2019-08-01 09:35:49.1661|TRACE|Packages|Security 1.0.1 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\Security.1.0.1.
2019-08-01 09:35:49.1661|TRACE|Packages|TMLShared 1.0.0 (requested from configuration file RhetosPackages.config) in C:\Business\BGA.All\backend\_build\PackagesCache\TMLShared.1.0.0.
2019-08-01 09:35:49.1891|INFO|Performance|00:00:25.6647953 PackageDownloader.GetPackages.
2019-08-01 09:35:49.2609|TRACE|DeployPackages|Loading plugins.
2019-08-01 09:35:51.7958|ERROR|DeployPackages|Rhetos.FrameworkException: Check for missing assembly or unsupported assembly version. Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
FileNotFoundException: Could not load file or assembly 'ServerDom.Model, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Rhetos.Extensibility.MefPluginScanner.LoadPlugins(List`1 assemblies) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\MefPluginScanner.cs:line 112
   at Rhetos.Extensibility.MefPluginScanner.FindPlugins(ContainerBuilder builder, Type pluginInterface) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\MefPluginScanner.cs:line 55
   --- End of inner exception stack trace ---
   at Rhetos.Extensibility.MefPluginScanner.FindPlugins(ContainerBuilder builder, Type pluginInterface) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\MefPluginScanner.cs:line 63
   at Rhetos.Extensibility.Plugins.FindAndRegisterPlugins[TPluginInterface](ContainerBuilder builder) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\Plugins.cs:line 72
   at DeployPackages.AutofacModuleConfiguration.Load(ContainerBuilder builder) in C:\My Projects\Rhetos\Source\DeployPackages\AutofacModuleConfiguration.cs:line 55
   at Autofac.Module.Configure(IComponentRegistry componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at DeployPackages.Program.GenerateApplication(ILogger logger, Arguments arguments) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 176
   at DeployPackages.Program.Main(String[] args) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 70
Info:

**Comment by ibarban** [comment]
Hi,
The probelm is that you are trying to use the ServerDom.Model.dll inside a a Rhetos package and this is not allowed becuse the package depends on a dll that does not yet exist.
The ServerDom.* dll's are generated a few steps later.
Can you describe what you are trying to achive?
Maybe I will be able to help you.

**Comment by JosipBaketaric** [comment]
I am trying to have one generic method that would generate some result.
Pretty simple. 
I will give you an example:

`
//ResultClass1 and ResultClass2 inherit BaseResultClass (rhetos defined datastructures)
public ResultClass1 method1()
{
....
return generateResult(something);
...
}

`public ResultClass2 method2()
{
....
return generateResult(something);
...
}`

private T generateResult<T>(T something) where T : BaseResultClass // rhetos class
{
Do something
return something;
}
`

**Comment by ibarban** [comment]
Yo can always create a concept that generates this code in ServerDom.
I don't know if you want to put this generic method in the Model or Repository class?
Also Rhetos does not use inhertiance (when using the standard concepts) when generating its models so I don't know how you would tell it that ResultClass1 and ResultClass2 inherit from BaseResultClass?

**Comment by bantolov** [comment]
I'll try the summarize the answers above and add some other options.

Since this custom dll (with your generic method) references ServerDom.Model.dll, it should be compiled *after* running DeployPackages (that generates ServerDom.Model.dll). It cannot be used as an input package for DeployPackages.

This issue will be obsolete after we finish integration with Visual Studio (#49). It will simplify development and eliminate this kind of problems by compiling custom classes and DSL-generated classes in a single pass.
Until then, there are three solutions that we can use in situations like this:

### Solution 1

You could eliminate reference from your dll to the ServerDom.Model.dll. This can by done removing `ClassDefinedInRhetosScript` from your method, and using some interface instead. The entity can implement this interface in the DSL script. For example:


```C#
// My custom C# project:

public ISomeInterface SomeMethod(ISomeInterface item)
{
    return ...;
}
...
public interface ISomeInterface
{
    string Name;
}

// My DSL script:

Entity SomeEntity
{
    ShortString Name;
    Implements 'ISomeInterface (use assembly-qualified name here)';
}
```

### Solution 2

You can add your class directly to ServerDom.Model.dll by implementing a [code generator](https://github.com/Rhetos/Rhetos/wiki/Rhetos-concept-development#how-to-write-a-concept-with-code-generator).
If you just need to add a single method, you can do it in DSL script with [RepositoryMember](https://github.com/Rhetos/Rhetos/wiki/Low-level-object-model-concepts#repositorymember) on Rhetos v2.11 or later.

### Solution 3

You can use the generated classes from the DSL scripts in your custom dll directly, but then you need to compile your dll *after* running DeployPackages (that generates ServerDom.Model.dll).
You can than add a post-build event in your project to copy your dll into the RhetosServer\bin\Plugins folder, so that it will be available at the runtime.
