### ISSUE TITLE
Fastreplacer throws exception if replacement text contains empty token

### ISSUE THREAD

**Issue by Markarend** [Rhetos/Rhetos#275]
When using   FastReplacer fr = new FastReplacer("{", "}")
If the input text contains "{}" then an exception is thrown:
{System.ArgumentException: Token has no body. Used with text "Ma{}rk".
   at Rhetos.Utilities.FastReplacer.ValidateToken(String token, String context, Boolean alreadyValidatedStartAndEnd)
   at Rhetos.Utilities.FastReplacer.ExtractTokens(FastReplacerSnippet snippet)
   at Rhetos.Utilities.FastReplacer.Replace(String token, String text)

Using delimiters in the replacement text works when there is any character between them.

**Comment by bantolov** [comment]
Hi,
Please elaborate what should be the expected behavior.

This exception was implemented to early detect errors when accidentally generating a token with a null object, resulting with empty token "{}". If not detected on time, this kind of error can sometimes manifest itself much later on a completely different project, when trying to extend an existing application by inserting some code at the token position.

**Comment by Markarend** [comment]
Bojan, I expect delimiters in the "text" parameter of FastReplacer.Replace to be ignored.

What I found is that when delimiters are found in the "text" parameter, they must represent non-null well-formed tokens themselves, or an error results.  Unless there's some sort of token recursion feature I'm not aware of.

Example in C# .NET:

                string html = "Patient Name: {PatientFirstName} {PatientLastName} <br/>Phone #: {PatientPhone} <br/>Email: {PatientEmail}";

                FastReplacer fr = new FastReplacer("{", "}");
                fr.Append(html);

                // The following succeed:
                fr.Replace("{PatientFirstName}", "Mark");

                // The following throw exceptions:
                fr.Replace("{PatientLastName}", "Are{}nd");
                fr.Replace("{PatientPhone}", "202-345-6789}");
                fr.Replace("{PatientEmail}", "markarend{@msn.com");

Thanks for your reply,

Mark Arend
704-641-8645 (cell)


________________________________

**Comment by bantolov** [comment]
You are correct, we often use FastReplacer with *recursive* token evaluation: The inserted text contains new tokens, which can again be replaced with some additional text.

I think it makes sense to support replacing token with an exact **"final" text**, that will not be evaluated for more tokens, and has **no restrictions** on what it contains.

We could simply add an optional bool parameter to FastReplacer methods to allow this.
The usage would look like this:

```c#
fr.Replace("{PatientLastName}", "Are{}nd", final: true);
```

What do think about this solution?

**Comment by bantolov** [comment]
Another possible approach would be to add a parameter to the constructor (whether to allow recursive token evaluation or not). It might simplify the usage, without adding a new parameter on each method.

```c#
FastReplacer fr = new FastReplacer("{", "}", resursiveEvaluation: false);
fr.Append(html);
fr.Replace("{PatientLastName}", "Are{}nd");
fr.Replace("{PatientPhone}", "202-345-6789}");
fr.Replace("{PatientEmail}", "markarend{@msn.com");
```
