### ISSUE TITLE
SqlException "Invalid object name" on database upgrade

### ISSUE THREAD

**Issue by bantolov** [Rhetos/Rhetos#369]
_[FAQ] Posting this as Frequently Asked Question._

DeployPackages.exe or rhetos.exe throws an SqlException "Invalid object name" on database upgrade.
What is causing the error?

Here is an example output log of Rhetos database update:

```log
[Info] DatabaseGenerator: Removing 0 concept applications.
[Info] DatabaseGenerator: Creating 4978 concept applications.
[Error] MsSqlExecuter: Unable to execute SQL query:
CREATE ...
...
[Error] DeployPackages: Rhetos.FrameworkException: SqlException has occurred:
Msg 208, Level 16, State 1, Procedure Legacy2, Line 9
Invalid object name 'X.Y'.
 ---> System.Data.SqlClient.SqlException: Invalid object name 'X.Y'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
...
```

**Comment by bantolov** [comment]
This is error commonly occurs when there is **missing dependency** between database objects, that Rhetos is not aware of.
For example, when a database view (SqlQuerable in DSL script) depends on some table, it must be created *after* the table is created, otherwise the error will occur in database when creating the view: "Invalid object name 'tablename'".

**To assure the correct order when creating database objects, you should state the dependency between the objects in DSL script.**
This is usually done by using AutoDetectSqlDependencies concept on a module, or on the dependent object.
See the section "Dependencies between database objects"(https://github.com/Rhetos/Rhetos/wiki/Database-objects#dependencies-between-database-objects) in documentation.

Remarks:

1. This error can occur unexpectedly when deploying to an empty database or **upgrading to a newer version of Rhetos**. In such situation, the dependent database objects where previously executed in the correct order by accident, and then after some change in internal ordering of concepts, deployment resulted with an error showing that there is a missing dependency.

2. There is a limitation with AutoDetectSqlDependencies: It does not analyze custom code in SqlObject concepts, therefore if an SqlQueryable (for example) depends on something that was **created by SqlObject**, you should state the dependency in the SqlQueryable by adding `SqlDependsOnSqlObject 'ModuleName.SqlObjectName';`.
