### ISSUE TITLE
Exception during build due to double quotes in the comment - SqlQueryable

### ISSUE THREAD

**Issue by MSvabenic** [Rhetos/Rhetos#57]
```
    SqlQueryable BookInfo
    "
    SELECT
        k.ID,
        CommentCount = COUNT(kom.ID), --this is a "simple" comment
        FullName = o.Name+ ' : ' + k.Title
    FROM
        BookStore.Book k
        LEFT JOIN BookStore.Comment kom ON kom.KnjigaID = k.ID
        LEFT JOIN BookStore.Person o ON o.ID = k.AutorID
        GROUP BY
        k.ID, o.Name, k.Title
        
    "
    {
        Extends BookStore.Book;
        Integer CommentCount ;
        ShortString FullName;
    }
```
Build will throw exception because of **"simple"** part of the comment.

Exception message:
```
DslSyntaxException: At line 204, column 60, file 'BookStore\DslScripts\BookStore.rhe',
after: "...nfo " SELECT k.ID, CommentCount = COUNT(kom.ID), --this is a simple "",
before: "comment" FullName = o.Name+ ' : ' + k.Title FROM BookStore.Book L...".
Previous concept: SqlQueryable BookStore.BookInfo
Property SqlSource (String) =
    SELECT
        k.ID,
        CommentCount = COUNT(kom.ID), --this is a simple
Property Module (ModuleInfo) = BookStore
Property Name (String) = BookInfo
Expected ";" or "{".
```
Call stack:
```
[Error] DeployPackages: Rhetos.Dsl.DslSyntaxException: At line 204, column 60, file 'BookStore\DslScripts\BookStore.rhe',
after: "...nfo " SELECT k.ID, CommentCount= COUNT(kom.ID), --this is a simple "",
before: "comment" FullName = o.Name+ ' : ' + k.Title FROM BookStore.Book k L...".
Previous concept: SqlQueryable BookStore.BookInfo
Property SqlSource (String) =
    SELECT
        k.ID,
        CommentCount= COUNT(kom.ID), --this is a simple
Property Module (ModuleInfo) = BookStore
Property Name (String) = BookInfo
Expected ";" or "{".
   at Rhetos.Dsl.DslParser.UpdateContextForNextConcept(TokenReader tokenReader, Stack`1 context, IConceptInfo conceptInfo) in \Rhetos\Source\Rhetos.Dsl\DslParser.cs:line 206
   at Rhetos.Dsl.DslParser.ExtractConcepts(IEnumerable`1 conceptParsers) in \Rhetos\Source\Rhetos.Dsl\DslParser.cs:line 109
   at Rhetos.Dsl.DslParser.get_ParsedConcepts() in \Rhetos\Source\Rhetos.Dsl\DslParser.cs:line 53
   at Rhetos.Dsl.DslModel.Initialize() in \Rhetos\Source\Rhetos.Dsl\DslModel.cs:line 114
   at Rhetos.Dsl.DslModel.get_Concepts() in \Rhetos\Source\Rhetos.Dsl\DslModel.cs:line 75
   at Rhetos.Deployment.ApplicationGenerator.ExecuteGenerators(Boolean deployDatabaseOnly) in \Rhetos\Source\Rhetos.Deployment\ApplicationGenerator.cs:line 79
   at DeployPackages.Program.GenerateApplication(ILogger logger, Arguments arguments) in \Rhetos\Source\DeployPackages\Program.cs:line 183
   at DeployPackages.Program.Main(String[] args) in i\Rhetos\Source\DeployPackages\Program.cs:line 69
Info:

```

**Comment by bantolov** [comment]
Than you for the report. Please append the exception message and call stack.
