### ISSUE TITLE
Runing DeployPackages.exe /DatabaseOnly from remote computer returns error

### ISSUE THREAD

**Issue by marijok** [Rhetos/Rhetos#60]
We are trying to run DeployPackages.exe /DatabaseOnly on a remote test application server from our release agent machine. These are two different computers on different domains. The script that is executed looks like
`net use x: \\ipadress\path password /user:username`
`x:\Rhetos\bin\DeployPackages.exe /DatabaseOnly`
`net use x: /d`

The error is:

```
2018-09-27T14:00:17.1157500Z [Info] DeployPackages: Skipped deleting old generated files (DeployDatabaseOnly).
2018-09-27T14:00:17.1972167Z [Info] DeployPackages: Skipped download packages (DeployDatabaseOnly).
2018-09-27T14:00:17.5031830Z [Trace] DeployPackages: Loading plugins.
2018-09-27T14:00:18.1560397Z [Error] DeployPackages: System.IO.FileLoadException: Could not load file or assembly 'RestService, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
2018-09-27T14:00:18.1563409Z File name: 'RestService, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
2018-09-27T14:00:18.1566427Z    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
2018-09-27T14:00:18.1567840Z    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
2018-09-27T14:00:18.1568920Z    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
2018-09-27T14:00:18.1569609Z    at System.ComponentModel.Composition.Hosting.AssemblyCatalog.LoadAssembly(String codeBase)
2018-09-27T14:00:18.1570334Z    at System.ComponentModel.Composition.Hosting.AssemblyCatalog..ctor(String codeBase)
2018-09-27T14:00:18.1571084Z    at Rhetos.Extensibility.MefPluginScanner.<>c.<LoadPlugins>b__4_0(String a) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\MefPluginScanner.cs:line 94
2018-09-27T14:00:18.1571727Z    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
2018-09-27T14:00:18.1572328Z    at System.Diagnostics.Contracts.Contract.ForAll[T](IEnumerable`1 collection, Predicate`1 predicate)
2018-09-27T14:00:18.1573141Z    at Microsoft.Internal.Requires.NotNullElements[T](IEnumerable`1 values, String parameterName)
2018-09-27T14:00:18.1573876Z    at System.ComponentModel.Composition.Hosting.AggregateCatalog..ctor(IEnumerable`1 catalogs)
2018-09-27T14:00:18.1574724Z    at Rhetos.Extensibility.MefPluginScanner.LoadPlugins(List`1 assemblies) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\MefPluginScanner.cs:line 95
2018-09-27T14:00:18.1575686Z    at Rhetos.Extensibility.MefPluginScanner.FindPlugins(ContainerBuilder builder, Type pluginInterface) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\MefPluginScanner.cs:line 55
2018-09-27T14:00:18.1581114Z    at Rhetos.Extensibility.Plugins.FindAndRegisterPlugins[TPluginInterface](ContainerBuilder builder) in C:\My Projects\Rhetos\Source\Rhetos.Extensibility\Plugins.cs:line 72
2018-09-27T14:00:18.1581952Z    at DeployPackages.AutofacModuleConfiguration.Load(ContainerBuilder builder) in C:\My Projects\Rhetos\Source\DeployPackages\AutofacModuleConfiguration.cs:line 55
2018-09-27T14:00:18.1582410Z    at Autofac.Module.Configure(IComponentRegistry componentRegistry)
2018-09-27T14:00:18.1582805Z    at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
2018-09-27T14:00:18.1583329Z    at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
2018-09-27T14:00:18.1583787Z    at DeployPackages.Program.GenerateApplication(ILogger logger, Arguments arguments) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 174
2018-09-27T14:00:18.1584342Z    at DeployPackages.Program.Main(String[] args) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 69
```
Has anybody run into this issue and how to we solve it? Tried to 'unblock' assembly but it didn't help. Also running DeployPackages.exe /DatabaseOnly on localy on application test server executes with no errors.

**Comment by tomostjepovic** [comment]
I also ran into the same issue last year, and just skipped it because I think there is a better way to do remote deploy (it is probably some problem with permissions, UAC).

On our project we do remote deploy on production and test enviroment in slightly different way, we copy all the needed files and powershell scripts on the remote machine and then execute those scripts which (among other things) run DeployPackages.exe with /DatabaseOnly switch. 
There is a predefined step in TFS Release/Build pipeline to execute remote PS scripts ([https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines?view=vsts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines?view=vsts)).

Let me know if you need any more help.

**Comment by marijok** [comment]
Thanks, used what @tomostjepovic suggested.
