### ISSUE TITLE
Cannot run CreateAndSetDatabase outside bin folder

### ISSUE THREAD

**Issue by nguyenquanghuy031295** [Rhetos/Rhetos#67]
**Describe the bug**
- I run **CreateAndSetDatabase.exe** by command line outside "bin" folder and it can't copy file **Template.ConnectionStrings.config**.
- It is same with **CreateIISExpressSite.exe**.

**To Reproduce**
Run command line outside "bin" folder like: 

> .\bin\CreateAndSetDatabase.exe "(local") "TestDatabase"

**Error message**
```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'Template.ConnectionStrings.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at CreateAndSetDatabase.Program.Main(String[] args) in C:\My Projects\Rhetos\Source\CreateAndSetDatabase\Program.cs:line 135
```

**Expected behavior**
It could copy **Template.ConnectionStrings.config** for creating **ConnectionStrings.config**.
I think problem is at here https://github.com/Rhetos/Rhetos/blob/afc283bd0b9f1dca95cb3c0b973ac9e6d6472324/Source/CreateAndSetDatabase/Program.cs#L134-L135)

**Comment by bantolov** [comment]
Fixed by PR #68
